#!/usr/bin/env python3

import re

# pour faire des tests
#file = open("petit-fichier2")

# Vrai fichier
file = open("fichier2")

# La somme des nombres trouvés
somme_total = 0

# Déclaration d'un dictionnaire pour mapper les mots anglais aux chiffres
CONVERSION = {'one': 'o1e', 'two': 't2o', 'three': 't3e', 'four': 'f4r',
              'five': 'f5e', 'six': 's6x', 'seven': 's7n', 'eight': 'e8t', 'nine': 'n9n'}

while True:    
    # On lit une ligne du fichier
    line = file.readline()
    
    # On valide que la ligne existe et non vide
    if line:  
        # Je dois convertir les mots en chiffres
        # Utiliser une expression régulière pour séparer les mots des chiffres
        mots_et_chiffres = re.findall(r'[a-zA-Z]+', line)        
        
        # Remplacer les occurrences des mots par les valeurs de la constante
        for mot, valeur in CONVERSION.items():
            line = line.replace(mot, valeur)        
                 
        # Créer une liste vide pour récupérer tout les numéros de la ligne
        liste_nombres = []
        
        # On boucle sur chaque caractère de la ligne
        for char in line:                        
            # On valide que le caractère est un chiffre
            if char.isdigit():
                # On ajoute le chiffre à la liste
                liste_nombres.append(int(char))
        
        # On valide que la liste n'est pas vide
        if len(liste_nombres) >= 2:
            # On doit extraire dernier chiffre pour les deux situations
            # Soit si nous avons un nombre entre 10 et 99 OU 100 et +, ça revient au même
            premier_chiffre = liste_nombres[0]
            dernier_chiffre = liste_nombres[-1]
            somme_total = somme_total + (premier_chiffre * 10) + dernier_chiffre
        
        else:
            # Nous avons alors un nombre à un digit, donc on doit le multiplier
            seul_chiffre = liste_nombres[0]
            somme_total = somme_total + (seul_chiffre * 11)            
    else:
        file.close()
        break    
    

# On affiche la somme total
print("La somme total est de: ", somme_total)    
'''
La somme total est de:  55093

real    0m0,109s
user    0m0,088s
sys     0m0,021s
'''
# Fin du script
