#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import string


# Fonction pour remplir la grille 2D avec un fichier
def remplir_grille(fichier):
    # Initialisation d'un tableau 2D pour recevoir des chiffres, avec des signes de ponctuation
    grille = []
    
    while True:    
        # On lit une ligne du fichier en retirant le retour à la ligne
        une_ligne = fichier.readline().strip()
        
        # On valide que la ligne existe et non vide
        if une_ligne:            
            # On ajout la ligne avec chaque caractère dans le tableau 2D, initialiser plus haut
            grille.append(list(une_ligne))
        else:
            # On ferme le fichier et on sort de la boucle
            fichier.close()
            break
    
    return grille


def main():
    
    # Ouverture du fichier
    fichier = open("petit-fichier")

    # On rempli la grille 2D avec le fichier
    grille = remplir_grille(fichier)
    
    # Besoin de connaitre le nombre de colonne et de ligne du tableau
    nb_colonne = len(grille[0])
    nb_ligne = len(grille)
    
    # Somme des parties du moteur
    somme_total = 0
    
    # On doit itérer la grille pour trouver les signes de ponctuations et faire des actions rendu là
    for x in range(nb_ligne):
        # On doit itérer sur les colonnes
        for y in range(nb_colonne):
            # On doit valider si c'est un signe de ponctuation
            if grille[x][y] in string.punctuation and grille[x][y] != ".":
                
                # On vérifi qu'on peut aller à droit pour commencer
                if y + 1 < nb_colonne:
                    # Valide un début de chiffre à droite              
                    if grille[x][y + 1].isdigit():
                        chiffre = ""
                        # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                        for yy in range(y + 1, nb_colonne):
                            if grille[x][yy] == ".":
                                break
                            else:
                                chiffre += grille[x][yy]
                        # Convertion du chiffre en entier
                        somme_total += int(chiffre)
                        print(chiffre)
                
                # On vérifi qu'on peut aller à gauche pour commencer
                if y - 1 >= 0:
                    # Valide un début de chiffre à gauche              
                    if grille[x][y - 1].isdigit():
                        chiffre = ""
                        # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                        for yy in range(y - 1, 0, -1):
                            if grille[x][yy] == ".":
                                break
                            else:
                                chiffre += grille[x][yy]
                        # On doit inverser le chiffre
                        chiffre = chiffre[::-1]
                        # Convertion du chiffre en entier
                        somme_total += int(chiffre)
                        print(chiffre)
                
                # On vérifi qu'on peut aller en bas pour commencer
                if x + 1 < nb_ligne:
                    # Valide qu'on n'a pas de chiffre en bas, mais peut-être en bas à gauche ou à droite         
                    if grille[x + 1][y] == ".":
                        # On est un étage plus bas (+1)
                        # On vérifi qu'on peut aller à droit et vérifier les chiffres
                        if y + 1 < nb_colonne and grille[x + 1][y + 1].isdigit():
                            chiffre = ""
                            # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                            for yy in range(y + 1, nb_colonne):
                                if grille[x + 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x + 1][yy]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        
                        # On vérifi qu'on peut aller à gauche et vérifier les chiffres
                        if y - 1 >= 0 and grille[x + 1][y - 1].isdigit():
                            chiffre = ""
                            # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                            # range(start, stop, step)
                            for yy in range(y - 1, 0, -1):
                                if grille[x + 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x + 1][yy]
                            # On doit inverser le chiffre
                            chiffre = chiffre[::-1]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                    else:
                        # On vérifi qu'on n'a pas de nombre à droite
                        if y + 1 < nb_colonne and grille[x + 1][y + 1] == ".":
                            chiffre = ""
                            # On extrait les chiffres en bas vers la gauche
                            for yy in range(y, 0, -1):
                                if grille[x + 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x + 1][yy]
                            # On doit inverser le chiffre
                            chiffre = chiffre[::-1]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        # On vérifi qu'on n'a pas de nombre à gauche  
                        elif y - 1 >= 0 and grille[x + 1][y - 1] == ".":
                            chiffre = ""
                            # On extrait les chiffres en bas vers la droite
                            for yy in range(y, nb_colonne):
                                if grille[x + 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x + 1][yy]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        elif y - 1 >= 0 and y + 1 < nb_colonne:
                            # On extrait les chiffres en bas, un pas à gauche et un pas à droite vers la gauche
                            chiffre = grille[x + 1][y - 1] + grille[x + 1][y] + grille[x + 1][y + 1]
                            chiffre = chiffre.replace(".", "") # C'est possible jusqu'à deux points                        
                            somme_total += int(chiffre)
                            print(chiffre)                            
                        
                # On vérifi qu'on peut aller en haut maintenant
                if x - 1 >= 0:
                    # Valide qu'on n'a pas de chiffre en haut, mais peut-être en haut à gauche ou à droite         
                    if grille[x - 1][y] == ".":
                        # On est un étage plus bas (+1)
                        # On vérifi qu'on peut aller à droit et vérifier les chiffres
                        if y + 1 < nb_colonne and grille[x - 1][y + 1].isdigit():
                            chiffre = ""
                            # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                            for yy in range(y + 1, nb_colonne):
                                if grille[x - 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x - 1][yy]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        
                        # On vérifi qu'on peut aller à gauche et vérifier les chiffres
                        if y - 1 >= 0 and grille[x - 1][y - 1].isdigit():
                            chiffre = ""
                            # On extrait les chiffres jusqu'à ce qu'on tombe sur un point.
                            # range(start, stop, step)
                            for yy in range(y - 1, 0, -1):
                                if grille[x - 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x - 1][yy]
                            # On doit inverser le premier et le dernier chiffre
                            chiffre = chiffre[::-1]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                    else:
                        # On vérifi qu'on n'a pas de nombre à droite
                        if y + 1 < nb_colonne and grille[x - 1][y + 1] == ".":
                            chiffre = ""
                            # On extrait les chiffres en haut vers la gauche
                            for yy in range(y, 0, -1):
                                if grille[x - 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x - 1][yy]
                            # On doit inverser le chiffre
                            chiffre = chiffre[::-1]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        # On vérifi qu'on n'a pas de nombre à gauche  
                        elif y - 1 >= 0 and grille[x - 1][y - 1] == ".":
                            chiffre = ""
                            # On extrait les chiffres en bas vers la droite
                            for yy in range(y, nb_colonne):
                                if grille[x - 1][yy] == ".":
                                    break
                                else:
                                    chiffre += grille[x - 1][yy]
                            # Convertion du chiffre en entier
                            somme_total += int(chiffre)
                            print(chiffre)
                        elif y - 1 >= 0 and y + 1 < nb_colonne:
                            # On extrait les chiffres en haut, un pas à gauche et un pas à droite vers la gauche
                            chiffre = grille[x - 1][y - 1] + grille[x - 1][y] + grille[x - 1][y + 1]
                            chiffre = chiffre.replace(".", "") # C'est possible jusqu'à deux points                        
                            somme_total += int(chiffre)
                            print(chiffre) 
                            
    # On affiche la somme total
    print("La somme total est de: ", somme_total)

# Appel de la fonction main
if __name__ == "__main__":
    main()
    
# Résultat:
'''
La somme total est de:  2105

real    0m0,059s
user    0m0,054s
sys     0m0,005s
'''